[package]
name = "rustboy"
version = "0.0.1"
authors = ["Matthias Reitinger <reima@edenprime.de>"]
edition = "2024"

[dependencies]
log = "0.4"
pixels = "0.15"
winit = { version = "0.30", features = ["rwh_05"] }
argh = "0.1"
